apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-app-config
  labels:
    backstage.io/kubernetes-id: {{ .Values.backstageLabel }}
data:
  app-config.production.yaml: |
    {{- toYaml .Values.config  | nindent 4 }}