apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: "sdjalskdju2asdasdwdwa398r7"
  labels:
    docs.crossplane.io/example: provider-aws
spec:
  forProvider:
    region: us-east-2
  providerConfigRef:
    name: default
