---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  owner: guests
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-website
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  links:
    - url: "https://backstage.k8s.sochacki.dev"
      title: Backstage
      icon: a
  description: Internal Developer Platform for all Developer! Find Information for your daily doing
  title: Internal Developer Platform
  tags:
    - javascript
    - backstage
    - idp
  annotations:
    github.com/project-slug: pascal-sochacki/BackstageTalk
    backstage.io/view-url: https://github.com/pascal-sochacki/BackstageTalk/blob/main/backstage/examples/entities.yaml
    backstage.io/edit-url: https://github.com/pascal-sochacki/BackstageTalk/edit/main/backstage/examples/entities.yaml
    backstage.io/techdocs-ref: dir:docs/backstage
    backstage.io/kubernetes-id: backstage
    prometheus.io/rule: container_memory_usage_bytes{image="ghcr.io/pascal-sochacki/backstagetalk:main"}
spec:
  type: website
  lifecycle: production
  system: internal-developer-platform
  owner: platform
  dependsOn:
    - resource:default/tech-docs-bucket
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-a
spec:
  type: website
  lifecycle: production
  system: product-a-system
  owner: product-team-a
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-b
spec:
  type: website
  lifecycle: production
  system: product-b-system
  owner: product-team-b
  providesApis:
    - open-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-c
spec:
  type: website
  lifecycle: production
  system: product-c-system
  owner: product-team-c
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tech-docs-bucket
  description: S3 Bucket for storing the techdocs
  tags:
    - aws
    - s3
spec:
  lifecycle: production
  type: s3-bucket
  system: internal-developer-platform
  owner: platform
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: internal-developer-platform
spec:
  owner: platform
  domain: platform
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: product-a-system
spec:
  owner: product-team-a
  domain: product-a
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: product-b-system
spec:
  owner: product-team-b
  domain: product-b
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: product-c-system
spec:
  owner: product-team-c
  domain: product-c
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: platform
spec:
  owner: platform
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: product-a
spec:
  owner: product-a
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: product-b
spec:
  owner: product-b
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: product-c
spec:
  owner: product-c
