site_name: "Backstage"

nav:
  - Home: index.md
  - More Page: more.md

plugins:
  - techdocs-core

repo_url: https://github.com/pascal-sochacki/BackstageTalk
edit_uri: edit/main/backstage/examples/docs/backstage/docs
