apiVersion: v2
name: services
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: ingress-nginx
    version: 4.0.13
    repository: https://kubernetes.github.io/ingress-nginx
  - name: kube-prometheus-stack
    version: 45.21.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: argo-cd
    version: 5.29.1
    repository: https://argoproj.github.io/argo-helm
  - name: cert-manager
    version: 1.11.1
    repository: https://charts.jetstack.io
  - name: crossplane
    version: 1.11.2
    repository: https://charts.crossplane.io/stable/