argo-cd:

  server:

    ingress:
      ingressClassName: nginx
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - argocd.k8s.sochacki.dev
      tls:
        - secretName: argocd-tls
          hosts:
            - argocd.k8s.sochacki.dev


  configs:
    rbac:
      policy.default: "role:admin"
    params:
      server.insecure: true
    cm:
      url: https://argocd.k8s.sochacki.dev
      dex.config: |
        connectors:
          # GitHub example
          - type: github
            id: github
            name: GitHub
            config:
              clientID: fca891413f5eaf127650
              clientSecret: $argocd:GITHUB_CLIENT_SECRET

